# Step 1 — Fine-tuned Baselines: BERT, HateBERT, and RoBERTa on IHC and ISHate

We fine-tune three pretrained models on two hate speech corpora (IHC and ISHate) and compare their macro F1 scores across both datasets.

In [1]:
# Uncomment if running in Colab
# !pip install -q transformers datasets accelerate scikit-learn

In [2]:
import numpy as np
from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)
from sklearn.metrics import f1_score, precision_score, recall_score, classification_report
import warnings
warnings.filterwarnings("ignore")

/usr/local/lib/python3.12/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Load the Datasets

### IHC (Implicit Hate Corpus)
`SALT-NLP/implicit-hate` was removed from the Hub — `tasksource/implicit-hate-stg1` is a verified mirror of the same IHC corpus (ElSherief et al., 2021). It has a single `train` split with 21,480 tweets labelled as `not_hate`, `explicit_hate`, or `implicit_hate`. Since there is no pre-made test split, we hold out 10% for evaluation. The binary label collapses explicit and implicit hate into a single **HS** class (label = 1); non-hate is **Non-HS** (label = 0).

### ISHate (Implicit and Subtle Hate Speech)
`BenjaminOcampo/ISHate` is a large-scale dataset (63,758 examples) focused on implicit and subtle hate speech, annotated with multiple layers. We use the `hateful_layer` column for binary classification (`Non-HS` → 0, `HS` → 1) and its pre-made train/test splits.

In [3]:
# IHC
raw = load_dataset("tasksource/implicit-hate-stg1", split="train")
splits = raw.train_test_split(test_size=0.10, seed=42)

def add_binary_label_ihc(example):
    example["label"] = 0 if example["class"] == "not_hate" else 1
    return example

train_ds = splits["train"].map(add_binary_label_ihc)
test_ds  = splits["test"].map(add_binary_label_ihc)

print("IHC")
print(f"  Train: {len(train_ds):,}  Test: {len(test_ds):,}")

# ISHate
ishate_raw = load_dataset("BenjaminOcampo/ISHate")

def add_binary_label_ishate(example):
    example["label"] = 0 if example["hateful_layer"] == "Non-HS" else 1
    return example

ishate_train = ishate_raw["train"].map(add_binary_label_ishate)
ishate_test  = ishate_raw["test"].map(add_binary_label_ishate)

print("\nISHate")
print(f"  Train: {len(ishate_train):,}  Test: {len(ishate_test):,}")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Generating train split:   0%|          | 0/21480 [00:00<?, ? examples/s]

Generating train split: 100%|██████████| 21480/21480 [00:00<00:00, 512119.79 examples/s]

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:  12%|█▏        | 2272/19332 [00:00<00:00, 22605.28 examples/s]

Map:  28%|██▊       | 5451/19332 [00:00<00:00, 21638.89 examples/s]

Map:  40%|███▉      | 7692/19332 [00:00<00:00, 21938.75 examples/s]

Map:  52%|█████▏    | 9995/19332 [00:00<00:00, 22329.66 examples/s]

Map:  69%|██████▉   | 13353/19332 [00:00<00:00, 22351.08 examples/s]

Map:  86%|████████▌ | 16539/19332 [00:00<00:00, 21923.22 examples/s]

Map:  97%|█████████▋| 18764/19332 [00:00<00:00, 22007.04 examples/s]

Map: 100%|██████████| 19332/19332 [00:00<00:00, 21763.74 examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Map:  83%|████████▎ | 1781/2148 [00:00<00:00, 17693.75 examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 16833.67 examples/s]

IHC
  Train: 19,332  Test: 2,148

Generating train split:   0%|          | 0/55023 [00:00<?, ? examples/s]

Generating train split: 100%|██████████| 55023/55023 [00:00<00:00, 874195.30 examples/s]

Generating validation split:   0%|          | 0/4367 [00:00<?, ? examples/s]

Generating validation split: 100%|██████████| 4367/4367 [00:00<00:00, 608603.32 examples/s]

Generating test split:   0%|          | 0/4368 [00:00<?, ? examples/s]

Generating test split: 100%|██████████| 4368/4368 [00:00<00:00, 602239.24 examples/s]

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   4%|▎         | 2000/55023 [00:00<00:03, 16855.73 examples/s]

Map:   7%|▋         | 4000/55023 [00:00<00:02, 18179.87 examples/s]

Map:  11%|█         | 6015/55023 [00:00<00:02, 18721.89 examples/s]

Map:  15%|█▍        | 8000/55023 [00:00<00:02, 18904.27 examples/s]

Map:  18%|█▊        | 10000/55023 [00:00<00:02, 17980.50 examples/s]

Map:  23%|██▎       | 12486/55023 [00:00<00:04, 9964.07 examples/s]

Map:  26%|██▌       | 14351/55023 [00:01<00:03, 11549.93 examples/s]

Map:  29%|██▉       | 16216/55023 [00:01<00:02, 13017.83 examples/s]

Map:  33%|███▎      | 18000/55023 [00:01<00:02, 13833.71 examples/s]

Map:  36%|███▋      | 20000/55023 [00:01<00:02, 14475.17 examples/s]

Map:  40%|███▉      | 22000/55023 [00:01<00:02, 15632.84 examples/s]

Map:  45%|████▍     | 24506/55023 [00:01<00:03, 9917.14 examples/s]

Map:  48%|████▊     | 26416/55023 [00:02<00:02, 11460.35 examples/s]

Map:  51%|█████     | 28115/55023 [00:02<00:02, 12529.56 examples/s]

Map:  55%|█████▍    | 30000/55023 [00:02<00:01, 13823.82 examples/s]

Map:  58%|█████▊    | 32000/55023 [00:02<00:01, 15120.43 examples/s]

Map:  62%|██████▏   | 34000/55023 [00:02<00:01, 16027.03 examples/s]

Map:  66%|██████▌   | 36150/55023 [00:02<00:01, 10408.70 examples/s]

Map:  69%|██████▉   | 38000/55023 [00:02<00:01, 11579.41 examples/s]

Map:  73%|███████▎  | 40000/55023 [00:03<00:01, 13210.26 examples/s]

Map:  76%|███████▋  | 42000/55023 [00:03<00:00, 14350.44 examples/s]

Map:  80%|███████▉  | 44000/55023 [00:03<00:00, 15605.64 examples/s]

Map:  84%|████████▎ | 46000/55023 [00:03<00:00, 16536.98 examples/s]

Map:  88%|████████▊ | 48560/55023 [00:03<00:00, 12088.54 examples/s]

Map:  92%|█████████▏| 50491/55023 [00:03<00:00, 13483.38 examples/s]

Map:  95%|█████████▌| 52420/55023 [00:03<00:00, 14738.39 examples/s]

Map:  99%|█████████▊| 54334/55023 [00:03<00:00, 15776.49 examples/s]

Map: 100%|██████████| 55023/55023 [00:04<00:00, 13657.07 examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Map:  46%|████▌     | 2000/4368 [00:00<00:00, 19580.75 examples/s]

Map:  99%|█████████▉| 4318/4368 [00:00<00:00, 10141.09 examples/s]

Map: 100%|██████████| 4368/4368 [00:00<00:00, 10666.51 examples/s]

ISHate
  Train: 55,023  Test: 4,368

## 2. Tokenization

Transformer models cannot work directly on raw text — they require a **tokenizer** that converts text into integer token IDs and an attention mask.

We truncate and pad every sequence to a fixed length of 128 tokens. Most tweets are well under this limit, so little information is lost. Each model has its own vocabulary and tokenizer, so we re-tokenize for each model.

In [4]:
def tokenize(ds, tokenizer, text_col="post", max_length=128):
    def _tok(batch):
        return tokenizer(
            batch[text_col],
            truncation=True,
            padding="max_length",
            max_length=max_length,
        )
    return ds.map(_tok, batched=True)

## 3. Metrics

The `Trainer` calls `compute_metrics` after each evaluation epoch. We use **macro F1** as the primary metric — it averages F1 across both classes, penalising models that ignore the minority class (hate speech). Precision and recall give additional diagnostic information.

In [5]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "macro_f1":  f1_score(labels, preds, average="macro",  zero_division=0),
        "macro_p":   precision_score(labels, preds, average="macro", zero_division=0),
        "macro_r":   recall_score(labels, preds, average="macro",    zero_division=0),
    }

## 4. Fine-tuning Loop

### What is a classification head?

A pretrained model like BERT has learned rich representations of text but has no built-in notion of hate speech. `AutoModelForSequenceClassification` adds a small **linear layer** (the classification head) on top of the `[CLS]` token representation, projecting it to 2 output logits (Non-HS, HS). This head is randomly initialised.

### What does fine-tuning do?

Fine-tuning runs gradient descent on the labelled IHC training set, updating **all** model weights — both the pretrained transformer layers and the new classification head. The pretrained weights are a warm start: the model has already learned grammar, semantics, and world knowledge, so it only needs a few epochs to adapt to the new task. Training from scratch would require far more data and compute.

In [6]:
MODELS = {
    "bert-base-uncased": "bert-base-uncased",
    "hateBERT":          "GroNLP/hateBERT",
    "roberta-base":      "roberta-base",
}

DATASETS = {
    "IHC":    {"train": train_ds,    "test": test_ds,    "text_col": "post"},
    "ISHate": {"train": ishate_train, "test": ishate_test, "text_col": "text"},
}

results = {}

for dataset_name, dataset in DATASETS.items():
    results[dataset_name] = {}
    for model_name, model_id in MODELS.items():
        print(f"\n{'='*60}")
        print(f"Dataset: {dataset_name}  |  Model: {model_name}")
        print(f"{'='*60}")

        tokenizer = AutoTokenizer.from_pretrained(model_id)
        model     = AutoModelForSequenceClassification.from_pretrained(model_id, num_labels=2)

        tok_train = tokenize(dataset["train"], tokenizer, text_col=dataset["text_col"])
        tok_test  = tokenize(dataset["test"],  tokenizer, text_col=dataset["text_col"])

        training_args = TrainingArguments(
            output_dir=f"./checkpoints/{dataset_name}/{model_name}",
            num_train_epochs=3,
            per_device_train_batch_size=16,
            per_device_eval_batch_size=32,
            learning_rate=2e-5,
            eval_strategy="epoch",
            save_strategy="no",
            logging_strategy="epoch",
            report_to="none",
            seed=42,
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=tok_train,
            eval_dataset=tok_test,
            compute_metrics=compute_metrics,
        )

        trainer.train()

        preds_output = trainer.predict(tok_test)
        preds  = np.argmax(preds_output.predictions, axis=-1)
        labels = dataset["test"]["label"]

        print(classification_report(labels, preds, target_names=["Non-HS", "HS"]))

        results[dataset_name][model_name] = {
            "macro_f1":  f1_score(labels, preds, average="macro",  zero_division=0),
            "macro_p":   precision_score(labels, preds, average="macro", zero_division=0),
            "macro_r":   recall_score(labels, preds, average="macro",    zero_division=0),
        }

============================================================
Dataset: IHC  |  Model: bert-base-uncased
============================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7577.34it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:   5%|▌         | 1000/19332 [00:00<00:01, 9877.01 examples/s]

Map:  16%|█▌        | 3000/19332 [00:00<00:01, 14647.34 examples/s]

Map:  26%|██▌       | 5000/19332 [00:00<00:00, 15587.06 examples/s]

Map:  36%|███▌      | 7000/19332 [00:00<00:00, 16084.76 examples/s]

Map:  47%|████▋     | 9000/19332 [00:00<00:00, 16617.80 examples/s]

Map:  57%|█████▋    | 11000/19332 [00:00<00:00, 16407.01 examples/s]

Map:  67%|██████▋   | 13000/19332 [00:00<00:00, 17159.21 examples/s]

Map:  78%|███████▊  | 15000/19332 [00:00<00:00, 17404.20 examples/s]

Map:  88%|████████▊ | 17000/19332 [00:01<00:00, 17643.88 examples/s]

Map:  98%|█████████▊| 19000/19332 [00:01<00:00, 17925.78 examples/s]

Map: 100%|██████████| 19332/19332 [00:01<00:00, 11539.87 examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Map:  93%|█████████▎| 2000/2148 [00:00<00:00, 13704.48 examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 12953.14 examples/s]

              precision    recall  f1-score   support

      Non-HS       0.83      0.86      0.85      1330
          HS       0.76      0.71      0.73       818

    accuracy                           0.80      2148
   macro avg       0.80      0.79      0.79      2148
weighted avg       0.80      0.80      0.80      2148

============================================================
Dataset: IHC  |  Model: hateBERT
============================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7651.52it/s]

BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:   5%|▌         | 1000/19332 [00:00<00:01, 9206.86 examples/s]

Map:  16%|█▌        | 3000/19332 [00:00<00:01, 15100.58 examples/s]

Map:  26%|██▌       | 5000/19332 [00:00<00:00, 15500.76 examples/s]

Map:  36%|███▌      | 7000/19332 [00:00<00:00, 14476.55 examples/s]

Map:  47%|████▋     | 9000/19332 [00:00<00:00, 14852.56 examples/s]

Map:  62%|██████▏   | 12000/19332 [00:00<00:00, 15919.96 examples/s]

Map:  72%|███████▏  | 14000/19332 [00:00<00:00, 15859.70 examples/s]

Map:  88%|████████▊ | 17000/19332 [00:01<00:00, 16869.53 examples/s]

Map:  98%|█████████▊| 19000/19332 [00:01<00:00, 16422.69 examples/s]

Map: 100%|██████████| 19332/19332 [00:01<00:00, 15610.96 examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Map:  93%|█████████▎| 2000/2148 [00:00<00:00, 12683.03 examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 12121.32 examples/s]

              precision    recall  f1-score   support

      Non-HS       0.82      0.87      0.84      1330
          HS       0.76      0.69      0.72       818

    accuracy                           0.80      2148
   macro avg       0.79      0.78      0.78      2148
weighted avg       0.80      0.80      0.80      2148

============================================================
Dataset: IHC  |  Model: roberta-base
============================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 7877.04it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.bias           | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:  16%|█▌        | 3000/19332 [00:00<00:00, 19339.17 examples/s]

Map:  36%|███▌      | 7000/19332 [00:00<00:00, 21615.80 examples/s]

Map:  52%|█████▏    | 10000/19332 [00:00<00:00, 19221.31 examples/s]

Map:  62%|██████▏   | 12000/19332 [00:00<00:00, 18015.74 examples/s]

Map:  72%|███████▏  | 14000/19332 [00:00<00:00, 17502.60 examples/s]

Map:  83%|████████▎ | 16000/19332 [00:00<00:00, 17219.20 examples/s]

Map:  98%|█████████▊| 19000/19332 [00:01<00:00, 16935.48 examples/s]

Map: 100%|██████████| 19332/19332 [00:01<00:00, 17105.08 examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 15513.35 examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 15196.47 examples/s]

              precision    recall  f1-score   support

      Non-HS       0.83      0.87      0.85      1330
          HS       0.77      0.71      0.74       818

    accuracy                           0.81      2148
   macro avg       0.80      0.79      0.79      2148
weighted avg       0.81      0.81      0.81      2148

============================================================
Dataset: ISHate  |  Model: bert-base-uncased
============================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 9350.12it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   5%|▌         | 3000/55023 [00:00<00:03, 16656.53 examples/s]

Map:   9%|▉         | 5000/55023 [00:00<00:02, 17964.68 examples/s]

Map:  13%|█▎        | 7000/55023 [00:00<00:02, 17474.48 examples/s]

Map:  16%|█▋        | 9000/55023 [00:00<00:02, 17392.39 examples/s]

Map:  22%|██▏       | 12000/55023 [00:00<00:02, 17125.03 examples/s]

Map:  25%|██▌       | 14000/55023 [00:00<00:02, 16492.43 examples/s]

Map:  29%|██▉       | 16000/55023 [00:00<00:02, 16730.75 examples/s]

Map:  33%|███▎      | 18000/55023 [00:01<00:02, 16944.64 examples/s]

Map:  36%|███▋      | 20000/55023 [00:01<00:02, 16594.62 examples/s]

Map:  40%|███▉      | 22000/55023 [00:01<00:03, 8834.01 examples/s]

Map:  44%|████▎     | 24000/55023 [00:01<00:03, 9974.92 examples/s]

Map:  47%|████▋     | 26000/55023 [00:01<00:02, 11304.99 examples/s]

Map:  51%|█████     | 28000/55023 [00:02<00:02, 12631.25 examples/s]

Map:  55%|█████▍    | 30000/55023 [00:02<00:01, 13637.55 examples/s]

Map:  58%|█████▊    | 32000/55023 [00:02<00:01, 14514.27 examples/s]

Map:  64%|██████▎   | 35000/55023 [00:02<00:01, 16269.76 examples/s]

Map:  67%|██████▋   | 37000/55023 [00:02<00:01, 16265.61 examples/s]

Map:  71%|███████   | 39000/55023 [00:02<00:00, 16358.83 examples/s]

Map:  75%|███████▍  | 41000/55023 [00:02<00:00, 16697.96 examples/s]

Map:  78%|███████▊  | 43000/55023 [00:02<00:00, 16370.79 examples/s]

Map:  82%|████████▏ | 45000/55023 [00:03<00:01, 8461.93 examples/s]

Map:  85%|████████▌ | 47000/55023 [00:03<00:00, 9314.34 examples/s]

Map:  89%|████████▉ | 49000/55023 [00:03<00:00, 10326.91 examples/s]

Map:  93%|█████████▎| 51000/55023 [00:03<00:00, 11525.85 examples/s]

Map:  96%|█████████▋| 53000/55023 [00:03<00:00, 12260.71 examples/s]

Map: 100%|█████████▉| 55000/55023 [00:04<00:00, 12520.92 examples/s]

Map: 100%|██████████| 55023/55023 [00:04<00:00, 12950.84 examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Map:  46%|████▌     | 2000/4368 [00:00<00:00, 12410.40 examples/s]

Map:  92%|█████████▏| 4000/4368 [00:00<00:00, 15054.43 examples/s]

Map: 100%|██████████| 4368/4368 [00:00<00:00, 14034.00 examples/s]

              precision    recall  f1-score   support

      Non-HS       0.90      0.90      0.90      2681
          HS       0.84      0.85      0.84      1687

    accuracy                           0.88      4368
   macro avg       0.87      0.87      0.87      4368
weighted avg       0.88      0.88      0.88      4368

============================================================
Dataset: ISHate  |  Model: hateBERT
============================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 9437.34it/s]

BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   5%|▌         | 3000/55023 [00:00<00:03, 15758.54 examples/s]

Map:   9%|▉         | 5000/55023 [00:00<00:02, 17382.19 examples/s]

Map:  15%|█▍        | 8000/55023 [00:00<00:02, 19076.74 examples/s]

Map:  18%|█▊        | 10000/55023 [00:00<00:02, 19271.56 examples/s]

Map:  24%|██▎       | 13000/55023 [00:00<00:02, 20119.53 examples/s]

Map:  29%|██▉       | 16000/55023 [00:00<00:02, 19397.61 examples/s]

Map:  33%|███▎      | 18000/55023 [00:00<00:01, 19360.23 examples/s]

Map:  38%|███▊      | 21000/55023 [00:01<00:03, 10697.71 examples/s]

Map:  44%|████▎     | 24000/55023 [00:01<00:02, 12322.38 examples/s]

Map:  47%|████▋     | 26000/55023 [00:01<00:02, 13250.54 examples/s]

Map:  51%|█████     | 28000/55023 [00:01<00:01, 14351.67 examples/s]

Map:  55%|█████▍    | 30000/55023 [00:01<00:01, 15371.87 examples/s]

Map:  60%|█████▉    | 33000/55023 [00:02<00:01, 16507.50 examples/s]

Map:  65%|██████▌   | 36000/55023 [00:02<00:01, 16865.78 examples/s]

Map:  69%|██████▉   | 38000/55023 [00:02<00:01, 16856.78 examples/s]

Map:  75%|███████▍  | 41000/55023 [00:02<00:00, 17701.92 examples/s]

Map:  80%|███████▉  | 44000/55023 [00:03<00:01, 10484.70 examples/s]

Map:  84%|████████▎ | 46000/55023 [00:03<00:00, 11145.20 examples/s]

Map:  87%|████████▋ | 48000/55023 [00:03<00:00, 12167.12 examples/s]

Map:  91%|█████████ | 50000/55023 [00:03<00:00, 12890.89 examples/s]

Map:  95%|█████████▍| 52000/55023 [00:03<00:00, 13355.00 examples/s]

Map:  98%|█████████▊| 54000/55023 [00:03<00:00, 13672.54 examples/s]

Map: 100%|██████████| 55023/55023 [00:03<00:00, 14048.84 examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Map:  46%|████▌     | 2000/4368 [00:00<00:00, 12633.73 examples/s]

Map:  92%|█████████▏| 4000/4368 [00:00<00:00, 14448.59 examples/s]

Map: 100%|██████████| 4368/4368 [00:00<00:00, 14018.08 examples/s]

              precision    recall  f1-score   support

      Non-HS       0.90      0.91      0.90      2681
          HS       0.85      0.84      0.85      1687

    accuracy                           0.88      4368
   macro avg       0.88      0.87      0.88      4368
weighted avg       0.88      0.88      0.88      4368

============================================================
Dataset: ISHate  |  Model: roberta-base
============================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 4342.89it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.bias           | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   5%|▌         | 3000/55023 [00:00<00:02, 17909.96 examples/s]

Map:  13%|█▎        | 7000/55023 [00:00<00:02, 19603.79 examples/s]

Map:  20%|█▉        | 11000/55023 [00:00<00:02, 19789.74 examples/s]

Map:  24%|██▎       | 13000/55023 [00:00<00:02, 19801.70 examples/s]

Map:  27%|██▋       | 15000/55023 [00:00<00:02, 19568.96 examples/s]

Map:  33%|███▎      | 18000/55023 [00:00<00:01, 19758.28 examples/s]

Map:  36%|███▋      | 20000/55023 [00:01<00:01, 19177.72 examples/s]

Map:  44%|████▎     | 24000/55023 [00:01<00:01, 19699.09 examples/s]

Map:  49%|████▉     | 27000/55023 [00:01<00:01, 20083.22 examples/s]

Map:  55%|█████▍    | 30000/55023 [00:01<00:02, 11527.31 examples/s]

Map:  62%|██████▏   | 34000/55023 [00:02<00:01, 14029.22 examples/s]

Map:  69%|██████▉   | 38000/55023 [00:02<00:01, 16264.61 examples/s]

Map:  76%|███████▋  | 42000/55023 [00:02<00:00, 17894.73 examples/s]

Map:  82%|████████▏ | 45000/55023 [00:02<00:00, 18734.88 examples/s]

Map:  87%|████████▋ | 48000/55023 [00:02<00:00, 18224.32 examples/s]

Map:  93%|█████████▎| 51000/55023 [00:02<00:00, 18714.36 examples/s]

Map:  96%|█████████▋| 53000/55023 [00:02<00:00, 18558.75 examples/s]

Map: 100%|█████████▉| 55000/55023 [00:03<00:00, 17807.41 examples/s]

Map: 100%|██████████| 55023/55023 [00:03<00:00, 17222.38 examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Map:  46%|████▌     | 2000/4368 [00:00<00:00, 15995.12 examples/s]

Map: 100%|██████████| 4368/4368 [00:00<00:00, 18105.93 examples/s]

Map: 100%|██████████| 4368/4368 [00:00<00:00, 17478.53 examples/s]

              precision    recall  f1-score   support

      Non-HS       0.91      0.91      0.91      2681
          HS       0.86      0.86      0.86      1687

    accuracy                           0.89      4368
   macro avg       0.89      0.89      0.89      4368
weighted avg       0.89      0.89      0.89      4368

## 5. Results

One table per dataset shows macro F1/P/R for all three models. Comparing across datasets reveals whether model rankings are consistent or dataset-dependent — e.g., whether HateBERT's domain-specific pretraining helps more on ISHate's subtler examples than on IHC.

In [7]:
import pandas as pd

for dataset_name, dataset_results in results.items():
    df = pd.DataFrame(dataset_results).T
    df.columns = ["Macro F1", "Macro Precision", "Macro Recall"]
    df.index.name = "Model"
    styled = df.style.format("{:.3f}").highlight_max(axis=0, props="font-weight: bold; background-color: #d4f1d4").set_caption(dataset_name)
    display(styled)