# Step 1 — Fine-tuned Baselines: BERT, HateBERT, and RoBERTa on IHC and ISHate

We fine-tune three pretrained models on two hate speech corpora (IHC and ISHate) and compare their macro F1 scores across both datasets.

In [1]:
# Uncomment if running in Colab
# !pip install -q transformers datasets accelerate scikit-learn

In [2]:
import os
import numpy as np
from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)
from sklearn.metrics import f1_score, precision_score, recall_score, classification_report
import warnings
warnings.filterwarnings("ignore")

/usr/local/lib/python3.12/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Load the Datasets

### IHC (Implicit Hate Corpus)
`SALT-NLP/implicit-hate` was removed from the Hub — `tasksource/implicit-hate-stg1` is a verified mirror of the same IHC corpus (ElSherief et al., 2021). It has a single `train` split with 21,480 tweets labelled as `not_hate`, `explicit_hate`, or `implicit_hate`. Since there is no pre-made test split, we hold out 10% for evaluation. The binary label collapses explicit and implicit hate into a single **HS** class (label = 1); non-hate is **Non-HS** (label = 0).

### ISHate (Implicit and Subtle Hate Speech)
`BenjaminOcampo/ISHate` is a large-scale dataset (63,758 examples) focused on implicit and subtle hate speech, annotated with multiple layers. We use the `hateful_layer` column for binary classification (`Non-HS` → 0, `HS` → 1) and its pre-made train/test splits.

In [3]:
# IHC
raw = load_dataset("tasksource/implicit-hate-stg1", split="train")
splits = raw.train_test_split(test_size=0.10, seed=42)

def add_binary_label_ihc(example):
    example["label"] = 0 if example["class"] == "not_hate" else 1
    return example

train_ds = splits["train"].map(add_binary_label_ihc)
test_ds  = splits["test"].map(add_binary_label_ihc)

print("IHC")
print(f"  Train: {len(train_ds):,}  Test: {len(test_ds):,}")

# ISHate
ishate_raw = load_dataset("BenjaminOcampo/ISHate")

def add_binary_label_ishate(example):
    example["label"] = 0 if example["hateful_layer"] == "Non-HS" else 1
    return example

ishate_train = ishate_raw["train"].map(add_binary_label_ishate)
ishate_test  = ishate_raw["test"].map(add_binary_label_ishate)

print("\nISHate")
print(f"  Train: {len(ishate_train):,}  Test: {len(ishate_test):,}")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Generating train split:   0%|          | 0/21480 [00:00<?, ? examples/s]

Generating train split: 100%|██████████| 21480/21480 [00:00<00:00, 562431.49 examples/s]

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:  11%|█         | 2161/19332 [00:00<00:00, 21472.21 examples/s]

Map:  28%|██▊       | 5437/19332 [00:00<00:00, 21720.72 examples/s]

Map:  45%|████▌     | 8732/19332 [00:00<00:00, 21835.64 examples/s]

Map:  57%|█████▋    | 10943/19332 [00:00<00:00, 21921.07 examples/s]

Map:  68%|██████▊   | 13148/19332 [00:00<00:00, 21958.73 examples/s]

Map:  80%|███████▉  | 15417/19332 [00:00<00:00, 22183.02 examples/s]

Map:  97%|█████████▋| 18736/19332 [00:00<00:00, 22155.04 examples/s]

Map: 100%|██████████| 19332/19332 [00:00<00:00, 21878.35 examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Map:  97%|█████████▋| 2073/2148 [00:00<00:00, 20498.90 examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 19919.88 examples/s]

IHC
  Train: 19,332  Test: 2,148

Generating train split:   0%|          | 0/55023 [00:00<?, ? examples/s]

Generating train split: 100%|██████████| 55023/55023 [00:00<00:00, 1102248.07 examples/s]

Generating validation split:   0%|          | 0/4367 [00:00<?, ? examples/s]

Generating validation split: 100%|██████████| 4367/4367 [00:00<00:00, 619450.29 examples/s]

Generating test split:   0%|          | 0/4368 [00:00<?, ? examples/s]

Generating test split: 100%|██████████| 4368/4368 [00:00<00:00, 668737.04 examples/s]

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   4%|▎         | 2002/55023 [00:00<00:02, 18711.47 examples/s]

Map:   7%|▋         | 4000/55023 [00:00<00:02, 18504.24 examples/s]

Map:  11%|█         | 6009/55023 [00:00<00:02, 18842.94 examples/s]

Map:  15%|█▍        | 8018/55023 [00:00<00:02, 19304.58 examples/s]

Map:  19%|█▉        | 10711/55023 [00:00<00:03, 12155.22 examples/s]

Map:  23%|██▎       | 12687/55023 [00:00<00:03, 13807.57 examples/s]

Map:  27%|██▋       | 14690/55023 [00:00<00:02, 15281.16 examples/s]

Map:  30%|███       | 16508/55023 [00:01<00:02, 16011.79 examples/s]

Map:  35%|███▌      | 19376/55023 [00:01<00:02, 17103.25 examples/s]

Map:  39%|███▊      | 21272/55023 [00:01<00:01, 17567.84 examples/s]

Map:  43%|████▎     | 23603/55023 [00:01<00:02, 12386.26 examples/s]

Map:  46%|████▋     | 25537/55023 [00:01<00:02, 13751.82 examples/s]

Map:  50%|████▉     | 27486/55023 [00:01<00:01, 15007.41 examples/s]

Map:  54%|█████▎    | 29443/55023 [00:01<00:01, 16092.91 examples/s]

Map:  57%|█████▋    | 31277/55023 [00:02<00:01, 16663.08 examples/s]

Map:  60%|██████    | 33198/55023 [00:02<00:01, 17339.45 examples/s]

Map:  65%|██████▍   | 35625/55023 [00:02<00:01, 12898.57 examples/s]

Map:  68%|██████▊   | 37561/55023 [00:02<00:01, 14244.97 examples/s]

Map:  72%|███████▏  | 39517/55023 [00:02<00:01, 15464.55 examples/s]

Map:  75%|███████▌  | 41474/55023 [00:02<00:00, 16477.27 examples/s]

Map:  79%|███████▉  | 43422/55023 [00:02<00:00, 17258.69 examples/s]

Map:  82%|████████▏ | 45389/55023 [00:02<00:00, 17912.94 examples/s]

Map:  86%|████████▋ | 47532/55023 [00:03<00:00, 12885.60 examples/s]

Map:  90%|████████▉ | 49465/55023 [00:03<00:00, 14264.10 examples/s]

Map:  93%|█████████▎| 51394/55023 [00:03<00:00, 15439.46 examples/s]

Map:  97%|█████████▋| 53352/55023 [00:03<00:00, 16476.54 examples/s]

Map: 100%|██████████| 55023/55023 [00:03<00:00, 15517.18 examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Map:  47%|████▋     | 2033/4368 [00:00<00:00, 19841.40 examples/s]

Map: 100%|██████████| 4368/4368 [00:00<00:00, 10552.00 examples/s]

Map: 100%|██████████| 4368/4368 [00:00<00:00, 11202.72 examples/s]

ISHate
  Train: 55,023  Test: 4,368

## 2. Tokenization

Transformer models cannot work directly on raw text — they require a **tokenizer** that converts text into integer token IDs and an attention mask.

We truncate and pad every sequence to a fixed length of 128 tokens. Most tweets are well under this limit, so little information is lost. Each model has its own vocabulary and tokenizer, so we re-tokenize for each model.

In [4]:
def tokenize(ds, tokenizer, text_col="post", max_length=128):
    def _tok(batch):
        return tokenizer(
            batch[text_col],
            truncation=True,
            padding="max_length",
            max_length=max_length,
        )
    return ds.map(_tok, batched=True)

## 3. Metrics

The `Trainer` calls `compute_metrics` after each evaluation epoch. We use **macro F1** as the primary metric — it averages F1 across both classes, penalising models that ignore the minority class (hate speech). Precision and recall give additional diagnostic information.

In [5]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "macro_f1":  f1_score(labels, preds, average="macro",  zero_division=0),
        "macro_p":   precision_score(labels, preds, average="macro", zero_division=0),
        "macro_r":   recall_score(labels, preds, average="macro",    zero_division=0),
    }

## 4. Fine-tuning Loop

### What is a classification head?

A pretrained model like BERT has learned rich representations of text but has no built-in notion of hate speech. `AutoModelForSequenceClassification` adds a small **linear layer** (the classification head) on top of the `[CLS]` token representation, projecting it to 2 output logits (Non-HS, HS). This head is randomly initialised.

### What does fine-tuning do?

Fine-tuning runs gradient descent on the labelled IHC training set, updating **all** model weights — both the pretrained transformer layers and the new classification head. The pretrained weights are a warm start: the model has already learned grammar, semantics, and world knowledge, so it only needs a few epochs to adapt to the new task. Training from scratch would require far more data and compute.

In [6]:
MODELS = {
    "bert-base-uncased": "bert-base-uncased",
    "hateBERT":          "GroNLP/hateBERT",
    "roberta-base":      "roberta-base",
}

DATASETS = {
    "IHC":    {"train": train_ds,    "test": test_ds,    "text_col": "post"},
    "ISHate": {"train": ishate_train, "test": ishate_test, "text_col": "text"},
}

results = {}

for dataset_name, dataset in DATASETS.items():
    results[dataset_name] = {}
    for model_name, model_id in MODELS.items():
        print(f"\n{'='*60}")
        print(f"Dataset: {dataset_name}  |  Model: {model_name}")
        print(f"{'='*60}")

        tokenizer = AutoTokenizer.from_pretrained(model_id)
        model     = AutoModelForSequenceClassification.from_pretrained(model_id, num_labels=2)

        tok_train = tokenize(dataset["train"], tokenizer, text_col=dataset["text_col"])
        tok_test  = tokenize(dataset["test"],  tokenizer, text_col=dataset["text_col"])

        training_args = TrainingArguments(
            output_dir=f"./checkpoints/{dataset_name}/{model_name}",
            num_train_epochs=3,
            per_device_train_batch_size=16,
            per_device_eval_batch_size=32,
            learning_rate=2e-5,
            eval_strategy="epoch",
            save_strategy="no",
            logging_strategy="epoch",
            report_to="none",
            seed=42,
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=tok_train,
            eval_dataset=tok_test,
            compute_metrics=compute_metrics,
        )

        trainer.train()

        # Save fine-tuned weights in HuggingFace format for use in rag_step3_index.ipynb
        save_path = f"./weights/{model_name}_{dataset_name}"
        os.makedirs(save_path, exist_ok=True)
        trainer.save_model(save_path)
        tokenizer.save_pretrained(save_path)
        print(f"  Saved weights → {save_path}")

        preds_output = trainer.predict(tok_test)
        preds  = np.argmax(preds_output.predictions, axis=-1)
        labels = dataset["test"]["label"]

        print(classification_report(labels, preds, target_names=["Non-HS", "HS"]))

        results[dataset_name][model_name] = {
            "macro_f1":  f1_score(labels, preds, average="macro",  zero_division=0),
            "macro_p":   precision_score(labels, preds, average="macro", zero_division=0),
            "macro_r":   recall_score(labels, preds, average="macro",    zero_division=0),
        }

============================================================
Dataset: IHC  |  Model: bert-base-uncased
============================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8311.01it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:   5%|▌         | 1000/19332 [00:00<00:01, 9476.49 examples/s]

Map:  21%|██        | 4000/19332 [00:00<00:00, 15868.71 examples/s]

Map:  36%|███▌      | 7000/19332 [00:00<00:00, 18389.38 examples/s]

Map:  47%|████▋     | 9000/19332 [00:00<00:00, 17441.79 examples/s]

Map:  57%|█████▋    | 11000/19332 [00:00<00:00, 17479.51 examples/s]

Map:  67%|██████▋   | 13000/19332 [00:00<00:00, 17724.45 examples/s]

Map:  78%|███████▊  | 15000/19332 [00:00<00:00, 18113.69 examples/s]

Map:  88%|████████▊ | 17000/19332 [00:01<00:00, 11628.93 examples/s]

Map: 100%|██████████| 19332/19332 [00:01<00:00, 13780.31 examples/s]

Map: 100%|██████████| 19332/19332 [00:01<00:00, 15079.49 examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 14172.31 examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 13903.13 examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.00it/s]

  Saved weights → ./weights/bert-base-uncased_IHC

              precision    recall  f1-score   support

      Non-HS       0.82      0.86      0.84      1330
          HS       0.75      0.70      0.72       818

    accuracy                           0.80      2148
   macro avg       0.79      0.78      0.78      2148
weighted avg       0.80      0.80      0.80      2148

============================================================
Dataset: IHC  |  Model: hateBERT
============================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8053.21it/s]

BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:  16%|█▌        | 3000/19332 [00:00<00:01, 14505.77 examples/s]

Map:  26%|██▌       | 5000/19332 [00:00<00:00, 16089.29 examples/s]

Map:  36%|███▌      | 7000/19332 [00:00<00:00, 16840.57 examples/s]

Map:  52%|█████▏    | 10000/19332 [00:00<00:00, 18074.13 examples/s]

Map:  62%|██████▏   | 12000/19332 [00:00<00:00, 17924.21 examples/s]

Map:  72%|███████▏  | 14000/19332 [00:00<00:00, 17545.84 examples/s]

Map:  88%|████████▊ | 17000/19332 [00:00<00:00, 18588.63 examples/s]

Map:  98%|█████████▊| 19000/19332 [00:01<00:00, 18421.03 examples/s]

Map: 100%|██████████| 19332/19332 [00:01<00:00, 17558.29 examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Map:  93%|█████████▎| 2000/2148 [00:00<00:00, 5428.25 examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 5634.94 examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.04it/s]

  Saved weights → ./weights/hateBERT_IHC

              precision    recall  f1-score   support

      Non-HS       0.82      0.87      0.84      1330
          HS       0.76      0.69      0.72       818

    accuracy                           0.80      2148
   macro avg       0.79      0.78      0.78      2148
weighted avg       0.80      0.80      0.80      2148

============================================================
Dataset: IHC  |  Model: roberta-base
============================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 8128.02it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.out_proj.bias        | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:  16%|█▌        | 3000/19332 [00:00<00:00, 18765.71 examples/s]

Map:  36%|███▌      | 7000/19332 [00:00<00:00, 20700.56 examples/s]

Map:  57%|█████▋    | 11000/19332 [00:00<00:00, 22002.23 examples/s]

Map:  72%|███████▏  | 14000/19332 [00:00<00:00, 22113.29 examples/s]

Map:  93%|█████████▎| 18000/19332 [00:00<00:00, 22241.86 examples/s]

Map: 100%|██████████| 19332/19332 [00:00<00:00, 21525.80 examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 16561.15 examples/s]

Map: 100%|██████████| 2148/2148 [00:00<00:00, 16286.23 examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.04s/it]

  Saved weights → ./weights/roberta-base_IHC

              precision    recall  f1-score   support

      Non-HS       0.83      0.87      0.85      1330
          HS       0.77      0.71      0.74       818

    accuracy                           0.81      2148
   macro avg       0.80      0.79      0.79      2148
weighted avg       0.81      0.81      0.81      2148

============================================================
Dataset: ISHate  |  Model: bert-base-uncased
============================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7891.11it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   5%|▌         | 3000/55023 [00:00<00:03, 15695.60 examples/s]

Map:   9%|▉         | 5000/55023 [00:00<00:02, 17179.97 examples/s]

Map:  15%|█▍        | 8000/55023 [00:00<00:02, 17552.95 examples/s]

Map:  20%|█▉        | 11000/55023 [00:00<00:02, 17983.50 examples/s]

Map:  24%|██▎       | 13000/55023 [00:00<00:02, 17557.68 examples/s]

Map:  31%|███       | 17000/55023 [00:00<00:01, 19261.84 examples/s]

Map:  35%|███▍      | 19000/55023 [00:01<00:01, 19140.80 examples/s]

Map:  38%|███▊      | 21000/55023 [00:01<00:02, 11737.30 examples/s]

Map:  42%|████▏     | 23000/55023 [00:01<00:02, 12787.71 examples/s]

Map:  49%|████▉     | 27000/55023 [00:01<00:01, 15614.96 examples/s]

Map:  53%|█████▎    | 29000/55023 [00:01<00:01, 16144.27 examples/s]

Map:  58%|█████▊    | 32000/55023 [00:01<00:01, 16804.26 examples/s]

Map:  64%|██████▎   | 35000/55023 [00:02<00:01, 17460.72 examples/s]

Map:  69%|██████▉   | 38000/55023 [00:02<00:00, 18670.29 examples/s]

Map:  73%|███████▎  | 40000/55023 [00:02<00:00, 17560.74 examples/s]

Map:  76%|███████▋  | 42000/55023 [00:02<00:00, 17523.94 examples/s]

Map:  80%|███████▉  | 44000/55023 [00:02<00:00, 12370.00 examples/s]

Map:  84%|████████▎ | 46000/55023 [00:02<00:00, 13341.86 examples/s]

Map:  87%|████████▋ | 48000/55023 [00:03<00:00, 14391.20 examples/s]

Map:  91%|█████████ | 50000/55023 [00:03<00:00, 15119.58 examples/s]

Map:  95%|█████████▍| 52000/55023 [00:03<00:00, 15433.11 examples/s]

Map:  98%|█████████▊| 54000/55023 [00:03<00:00, 14746.68 examples/s]

Map: 100%|██████████| 55023/55023 [00:03<00:00, 15722.22 examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Map:  46%|████▌     | 2000/4368 [00:00<00:00, 13559.32 examples/s]

Map:  92%|█████████▏| 4000/4368 [00:00<00:00, 14690.02 examples/s]

Map: 100%|██████████| 4368/4368 [00:00<00:00, 14381.11 examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.10it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.10it/s]

  Saved weights → ./weights/bert-base-uncased_ISHate

              precision    recall  f1-score   support

      Non-HS       0.90      0.90      0.90      2681
          HS       0.84      0.85      0.84      1687

    accuracy                           0.88      4368
   macro avg       0.87      0.87      0.87      4368
weighted avg       0.88      0.88      0.88      4368

============================================================
Dataset: ISHate  |  Model: hateBERT
============================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8456.17it/s]

BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   4%|▎         | 2000/55023 [00:00<00:03, 13760.59 examples/s]

Map:   7%|▋         | 4000/55023 [00:00<00:03, 16216.81 examples/s]

Map:  13%|█▎        | 7000/55023 [00:00<00:02, 17242.16 examples/s]

Map:  18%|█▊        | 10000/55023 [00:00<00:02, 17716.75 examples/s]

Map:  24%|██▎       | 13000/55023 [00:00<00:02, 18376.51 examples/s]

Map:  27%|██▋       | 15000/55023 [00:00<00:02, 18482.05 examples/s]

Map:  31%|███       | 17000/55023 [00:00<00:02, 18382.59 examples/s]

Map:  35%|███▍      | 19000/55023 [00:01<00:01, 18659.82 examples/s]

Map:  38%|███▊      | 21000/55023 [00:01<00:03, 10514.00 examples/s]

Map:  44%|████▎     | 24000/55023 [00:01<00:02, 12732.48 examples/s]

Map:  47%|████▋     | 26000/55023 [00:01<00:02, 13811.46 examples/s]

Map:  51%|█████     | 28000/55023 [00:01<00:01, 14357.51 examples/s]

Map:  55%|█████▍    | 30000/55023 [00:01<00:01, 15103.58 examples/s]

Map:  60%|█████▉    | 33000/55023 [00:02<00:01, 15973.63 examples/s]

Map:  64%|██████▎   | 35000/55023 [00:02<00:01, 16647.39 examples/s]

Map:  67%|██████▋   | 37000/55023 [00:02<00:01, 16691.54 examples/s]

Map:  73%|███████▎  | 40000/55023 [00:02<00:00, 17263.41 examples/s]

Map:  78%|███████▊  | 43000/55023 [00:02<00:00, 17930.08 examples/s]

Map:  82%|████████▏ | 45000/55023 [00:02<00:00, 12944.34 examples/s]

Map:  85%|████████▌ | 47000/55023 [00:03<00:00, 13799.30 examples/s]

Map:  89%|████████▉ | 49000/55023 [00:03<00:00, 15030.71 examples/s]

Map:  93%|█████████▎| 51000/55023 [00:03<00:00, 16020.18 examples/s]

Map:  96%|█████████▋| 53000/55023 [00:03<00:00, 16713.17 examples/s]

Map: 100%|█████████▉| 55000/55023 [00:03<00:00, 16641.40 examples/s]

Map: 100%|██████████| 55023/55023 [00:03<00:00, 15652.11 examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Map:  69%|██████▊   | 3000/4368 [00:00<00:00, 14181.96 examples/s]

Map: 100%|██████████| 4368/4368 [00:00<00:00, 15035.57 examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.09it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.09it/s]

  Saved weights → ./weights/hateBERT_ISHate

              precision    recall  f1-score   support

      Non-HS       0.90      0.91      0.90      2681
          HS       0.85      0.84      0.85      1687

    accuracy                           0.88      4368
   macro avg       0.88      0.87      0.88      4368
weighted avg       0.88      0.88      0.88      4368

============================================================
Dataset: ISHate  |  Model: roberta-base
============================================================

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 8784.12it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.out_proj.bias        | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   5%|▌         | 3000/55023 [00:00<00:02, 18931.21 examples/s]

Map:  11%|█         | 6000/55023 [00:00<00:02, 20004.02 examples/s]

Map:  16%|█▋        | 9000/55023 [00:00<00:02, 20425.60 examples/s]

Map:  22%|██▏       | 12000/55023 [00:00<00:02, 19476.50 examples/s]

Map:  25%|██▌       | 14000/55023 [00:00<00:02, 18773.95 examples/s]

Map:  29%|██▉       | 16000/55023 [00:00<00:02, 18877.91 examples/s]

Map:  35%|███▍      | 19000/55023 [00:00<00:01, 19121.97 examples/s]

Map:  38%|███▊      | 21000/55023 [00:01<00:01, 18833.45 examples/s]

Map:  42%|████▏     | 23000/55023 [00:01<00:01, 18728.95 examples/s]

Map:  47%|████▋     | 26000/55023 [00:01<00:01, 19042.25 examples/s]

Map:  53%|█████▎    | 29000/55023 [00:01<00:01, 19488.29 examples/s]

Map:  58%|█████▊    | 32000/55023 [00:01<00:01, 19737.58 examples/s]

Map:  62%|██████▏   | 34000/55023 [00:01<00:01, 19052.86 examples/s]

Map:  65%|██████▌   | 36000/55023 [00:01<00:00, 19041.43 examples/s]

Map:  71%|███████   | 39000/55023 [00:02<00:00, 19239.30 examples/s]

Map:  75%|███████▍  | 41000/55023 [00:02<00:01, 12022.02 examples/s]

Map:  80%|███████▉  | 44000/55023 [00:02<00:00, 14110.56 examples/s]

Map:  84%|████████▎ | 46000/55023 [00:02<00:00, 14375.27 examples/s]

Map:  87%|████████▋ | 48000/55023 [00:02<00:00, 14752.85 examples/s]

Map:  91%|█████████ | 50000/55023 [00:02<00:00, 15634.18 examples/s]

Map:  95%|█████████▍| 52000/55023 [00:03<00:00, 15828.45 examples/s]

Map:  98%|█████████▊| 54000/55023 [00:03<00:00, 15633.42 examples/s]

Map: 100%|██████████| 55023/55023 [00:03<00:00, 17126.81 examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Map:  69%|██████▊   | 3000/4368 [00:00<00:00, 16970.59 examples/s]

Map: 100%|██████████| 4368/4368 [00:00<00:00, 17304.61 examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.14s/it]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.14s/it]

  Saved weights → ./weights/roberta-base_ISHate

              precision    recall  f1-score   support

      Non-HS       0.91      0.91      0.91      2681
          HS       0.86      0.86      0.86      1687

    accuracy                           0.89      4368
   macro avg       0.89      0.89      0.89      4368
weighted avg       0.89      0.89      0.89      4368

## 5. Results

One table per dataset shows macro F1/P/R for all three models. Comparing across datasets reveals whether model rankings are consistent or dataset-dependent — e.g., whether HateBERT's domain-specific pretraining helps more on ISHate's subtler examples than on IHC.

In [7]:
import pandas as pd

for dataset_name, dataset_results in results.items():
    df = pd.DataFrame(dataset_results).T
    df.columns = ["Macro F1", "Macro Precision", "Macro Recall"]
    df.index.name = "Model"
    styled = df.style.format("{:.3f}").highlight_max(axis=0, props="font-weight: bold; background-color: #d4f1d4").set_caption(dataset_name)
    display(styled)