# Fine-tuned Baselines: BERT, HateBERT, and RoBERTa

Fine-tune three pretrained models (BERT, HateBERT, RoBERTa) on three hate speech datasets (IHC, ISHate, Vicomtech) using standard binary cross-entropy training.

In [1]:
import os
import sys
from pathlib import Path
import numpy as np
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import f1_score, precision_score, recall_score, classification_report
import warnings
warnings.filterwarnings("ignore")

# add src/ to path so shared modules (retriever, data_loaders, ...) are importable
sys.path.insert(0, str(Path("..").resolve()))

## 1. Load the Datasets

Load IHC, ISHate and Vicomtech using `data_loaders.py`.

In [2]:
from data_loaders import load_ihc_binary, load_ishate_binary, load_vicomtech

# Load the 3 datasets using the functions in dataloaders.py and print the train/test lengths
train_ds, test_ds       = load_ihc_binary(seed=42)
ishate_train, ishate_test = load_ishate_binary()
vicomtech_train, vicomtech_test = load_vicomtech()

print("IHC")
print(f"  Train: {len(train_ds):,}  Test: {len(test_ds):,}")
print("\nISHate")
print(f"  Train: {len(ishate_train):,}  Test: {len(ishate_test):,}")
print("\n Vicomtech")
print(f"  Train: {len(vicomtech_train):,}  Test: {len(vicomtech_test):,}")

README.md:   0%|          | 0.00/792 [00:00<?, ?B/s]

implicit_hate_v1_stg1_posts.tsv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/21480 [00:00<?, ? examples/s]

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

ishate_train.parquet.gzip:   0%|          | 0.00/3.45M [00:00<?, ?B/s]

ishate_dev.parquet.gzip:   0%|          | 0.00/468k [00:00<?, ?B/s]

ishate_test.parquet.gzip:   0%|          | 0.00/479k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/55023 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/4367 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/4368 [00:00<?, ? examples/s]

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Downloading Vicomtech dataset from GitHub...

IHC
  Train: 19,332  Test: 2,148

ISHate
  Train: 55,023  Test: 4,368

 Vicomtech
  Train: 1,914  Test: 478

## 2. Tokenization

Tokenize each dataset using the model's own tokenizer, truncating and padding to 128 tokens.

In [3]:
def tokenize(ds, tokenizer, text_col="post", max_length=128):
    def _tok(batch):
        return tokenizer(
            batch[text_col],
            truncation=True,
            padding="max_length",
            max_length=max_length,
        )
    return ds.map(_tok, batched=True)

## 3. Metrics

We use macro F1 as the primary metric, with precision and recall as additional diagnostic values.

In [4]:
from training_utils import compute_metrics, set_seed

## 4. Fine-tuning Loop

For each (model, dataset) pair: load the pretrained weights, fine-tune for 3 epochs, save the weights, and print the classification report.

In [5]:
# Define a dictionnary of the baseline models "short name" and "real name"
MODELS = {
    "bert":     "bert-base-uncased",
    "hatebert": "GroNLP/hateBERT",
    "roberta":  "roberta-base",
}

# Create a dictionnary containing each datasets train/test data 
DATASETS = {
    "IHC":       {"train": train_ds,        "test": test_ds,        "text_col": "post"},
    "ISHate":    {"train": ishate_train,     "test": ishate_test,    "text_col": "text"},
    "Vicomtech": {"train": vicomtech_train,  "test": vicomtech_test, "text_col": "text"},
}

results = {}

# Go through every dataset
for dataset_name, dataset in DATASETS.items():
    results[dataset_name] = {}
    # Go through each model
    for model_name, model_id in MODELS.items():
        print(f"Dataset: {dataset_name}  |  Model: {model_name}")

        # Load model's tokenizer and model (with appropriate classification head added using AutoModelForSequenceClassification function)
        tokenizer = AutoTokenizer.from_pretrained(model_id)

        # Seed before model init so classifier head is reproducible across runs.
        # TrainingArguments(seed=42) only seeds the training loop, not from_pretrained().
        set_seed(42)
        model     = AutoModelForSequenceClassification.from_pretrained(model_id, num_labels=2)

        # Tokenize train/test data
        tok_train = tokenize(dataset["train"], tokenizer, text_col=dataset["text_col"])
        tok_test  = tokenize(dataset["test"],  tokenizer, text_col=dataset["text_col"])

        # Define the training hyperparameters and strategies
        training_args = TrainingArguments(
            output_dir=f"../../checkpoints_baseline/{dataset_name}/{model_name}",
            num_train_epochs=3,
            per_device_train_batch_size=16,
            per_device_eval_batch_size=32,
            learning_rate=2e-5,
            eval_strategy="epoch",
            save_strategy="no",
            logging_strategy="epoch",
            report_to="none",
            seed=42,
        )

        # Define the trainer
        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=tok_train,
            eval_dataset=tok_test,
            compute_metrics=compute_metrics,
        )

        # Train
        trainer.train()

        # Save fine-tuned weights in HuggingFace format
        save_path = f"../../weigths/weights_baseline/{model_name}/{dataset_name}"
        os.makedirs(save_path, exist_ok=True)
        trainer.save_model(save_path)
        tokenizer.save_pretrained(save_path)
        print(f"Saved weights → {save_path}")

        # Test the model
        preds_output = trainer.predict(tok_test)
        preds  = np.argmax(preds_output.predictions, axis=-1)
        labels = dataset["test"]["label"]

        # Prints its performances
        print(classification_report(labels, preds, target_names=["Non-HS", "HS"]))

        # Add them in the results table
        results[dataset_name][model_name] = {
            "macro_f1":  f1_score(labels, preds, average="macro",  zero_division=0),
            "macro_p":   precision_score(labels, preds, average="macro", zero_division=0),
            "macro_r":   recall_score(labels, preds, average="macro",    zero_division=0),
        }

Dataset: IHC  |  Model: bert

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Saved weights → ../../weigths/weights_baseline/bert/IHC

              precision    recall  f1-score   support

      Non-HS       0.83      0.86      0.84      1330
          HS       0.76      0.71      0.73       818

    accuracy                           0.80      2148
   macro avg       0.79      0.78      0.79      2148
weighted avg       0.80      0.80      0.80      2148

Dataset: IHC  |  Model: hatebert

tokenizer_config.json:   0%|          | 0.00/151 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at GroNLP/hateBERT and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Saved weights → ../../weigths/weights_baseline/hatebert/IHC

              precision    recall  f1-score   support

      Non-HS       0.82      0.87      0.84      1330
          HS       0.76      0.70      0.73       818

    accuracy                           0.80      2148
   macro avg       0.79      0.78      0.79      2148
weighted avg       0.80      0.80      0.80      2148

Dataset: IHC  |  Model: roberta

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/19332 [00:00<?, ? examples/s]

Map:   0%|          | 0/2148 [00:00<?, ? examples/s]

Saved weights → ../../weigths/weights_baseline/roberta/IHC

              precision    recall  f1-score   support

      Non-HS       0.83      0.87      0.85      1330
          HS       0.77      0.72      0.74       818

    accuracy                           0.81      2148
   macro avg       0.80      0.79      0.80      2148
weighted avg       0.81      0.81      0.81      2148

Dataset: ISHate  |  Model: bert

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Saved weights → ../../weigths/weights_baseline/bert/ISHate

              precision    recall  f1-score   support

      Non-HS       0.90      0.90      0.90      2681
          HS       0.85      0.84      0.84      1687

    accuracy                           0.88      4368
   macro avg       0.87      0.87      0.87      4368
weighted avg       0.88      0.88      0.88      4368

Dataset: ISHate  |  Model: hatebert

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at GroNLP/hateBERT and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Saved weights → ../../weigths/weights_baseline/hatebert/ISHate

              precision    recall  f1-score   support

      Non-HS       0.91      0.91      0.91      2681
          HS       0.85      0.86      0.85      1687

    accuracy                           0.89      4368
   macro avg       0.88      0.88      0.88      4368
weighted avg       0.89      0.89      0.89      4368

Dataset: ISHate  |  Model: roberta

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/55023 [00:00<?, ? examples/s]

Map:   0%|          | 0/4368 [00:00<?, ? examples/s]

Saved weights → ../../weigths/weights_baseline/roberta/ISHate

              precision    recall  f1-score   support

      Non-HS       0.92      0.89      0.90      2681
          HS       0.84      0.87      0.85      1687

    accuracy                           0.88      4368
   macro avg       0.88      0.88      0.88      4368
weighted avg       0.89      0.88      0.88      4368

Dataset: Vicomtech  |  Model: bert

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/1914 [00:00<?, ? examples/s]

Map:   0%|          | 0/478 [00:00<?, ? examples/s]

Saved weights → ../../weigths/weights_baseline/bert/Vicomtech

              precision    recall  f1-score   support

      Non-HS       0.81      0.82      0.81       239
          HS       0.82      0.81      0.81       239

    accuracy                           0.81       478
   macro avg       0.81      0.81      0.81       478
weighted avg       0.81      0.81      0.81       478

Dataset: Vicomtech  |  Model: hatebert

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at GroNLP/hateBERT and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/1914 [00:00<?, ? examples/s]

Map:   0%|          | 0/478 [00:00<?, ? examples/s]

Saved weights → ../../weigths/weights_baseline/hatebert/Vicomtech

              precision    recall  f1-score   support

      Non-HS       0.84      0.79      0.81       239
          HS       0.80      0.85      0.83       239

    accuracy                           0.82       478
   macro avg       0.82      0.82      0.82       478
weighted avg       0.82      0.82      0.82       478

Dataset: Vicomtech  |  Model: roberta

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/1914 [00:00<?, ? examples/s]

Map:   0%|          | 0/478 [00:00<?, ? examples/s]

Saved weights → ../../weigths/weights_baseline/roberta/Vicomtech

              precision    recall  f1-score   support

      Non-HS       0.82      0.85      0.83       239
          HS       0.84      0.81      0.82       239

    accuracy                           0.83       478
   macro avg       0.83      0.83      0.83       478
weighted avg       0.83      0.83      0.83       478

## 5. Results

One table per dataset showing macro F1, precision and recall for all three models.

In [6]:
import pandas as pd

# Display the results in a table using panda's functions
for dataset_name, dataset_results in results.items():
    df = pd.DataFrame(dataset_results).T
    df.columns = ["Macro F1", "Macro Precision", "Macro Recall"]
    df.index.name = "Model"
    styled = df.style.format("{:.3f}").highlight_max(axis=0, props="font-weight: bold; background-color: #d4f1d4").set_caption(dataset_name)
    display(styled)